# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# The composition tool's ram_align over the align table, beside the CMake copy's answers:
#
#   emit_align.py <scratch directory> <cases.txt> <table.h>
#
# Each case line is `<min region> <pow2> <stride, 0 for none> <want> <CMake's alignment>`.

import sys

from kickos_compose import supply
from kickos_compose.manifest import Manifest


def manifest_of(min_region, pow2, stride):
    manifest = Manifest()
    manifest.window_rule = "none"
    if min_region != 0:
        manifest.window_rule = "granule"
        if pow2 != 0:
            manifest.window_rule = "pow2"
    manifest.smallest_window = min_region
    manifest.stack_stride = None
    if stride != 0:
        manifest.stack_stride = stride
    return manifest


def main(argv):
    cases, table = argv[2], argv[3]
    rows = []
    with open(cases) as f:
        for line in f:
            if not line.strip():
                continue
            min_region, pow2, stride, want, cmake = (int(word) for word in line.split())
            python = supply.ram_align(want, manifest_of(min_region, pow2, stride))
            rows.append("    {%du, %d, %du, %du, %du, %du},"
                        % (min_region, pow2, stride, want, cmake, python))
    with open(table, "w") as f:
        f.write("// Generated by tests/unit/ramalign/emit_align.py.\n")
        f.write("#include <stddef.h>\n\n")
        f.write("struct AlignCase\n{\n    size_t min_region;\n    int pow2;\n    size_t stride;\n"
                "    size_t want;\n    size_t cmake;\n    size_t python;\n};\n\n")
        f.write("static AlignCase const ALIGN_CASES[] = {\n%s\n};\n" % "\n".join(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
