# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# The composition tool's RAM region rule over the region table, as the configure asks it for a
# 64-bit word: each row's size and alignment, or its refusal:
#
#   emit_align.py <scratch directory> <table.h>

import sys

from kickos_compose import region

STRIDES = (0, 8192)
# (arch_mpu_min_region, arch_mpu_region_pow2); a no-unit board scrapes pow2 1 off the v7-M fallback.
GEOMETRIES = ((0, 0), (0, 1), (32, 0), (64, 0), (256, 0), (32, 1), (256, 1))
WANTS = (0, 1, 16, 31, 96, 100, 512, 1000, 4096, 4097, 8160, 8172, 8192, 8193, 8224, 12000, 16384,
         0x80000001, 0x100000001, 0x8000000000000000, 0x8000000000000001, 0xFFFFFFFFFFFFFF00,
         0xFFFFFFFFFFFFFFE0, 0xFFFFFFFFFFFFFFF1, 0xFFFFFFFFFFFFFFFF)
WORD_BITS = 64


def main(argv):
    table = argv[2]
    rows = []
    for stride in STRIDES:
        for min_region, pow2 in GEOMETRIES:
            for want in WANTS:
                figures, refused = region.boot_figures([want], min_region, pow2, stride, WORD_BITS)
                size, align, said = 0, 0, "true"
                if refused is None:
                    (size, align), = figures
                    said = "false"
                rows.append("    {%du, %d, %du, %#xull, %#xull, %#xull, %s}," % (
                    min_region, pow2, stride, want, size, align, said))
    with open(table, "w") as f:
        f.write("// Generated by tests/unit/ramalign/emit_align.py.\n")
        f.write("#include <stddef.h>\n\n")
        f.write("#define REGION_WORD_BITS %d\n\n" % WORD_BITS)
        f.write("struct RegionCase\n{\n    size_t min_region;\n    int pow2;\n    size_t stride;\n"
                "    size_t want;\n    size_t size;\n    size_t align;\n    bool refused;\n};\n\n")
        f.write("static RegionCase const REGION_CASES[] = {\n%s\n};\n" % "\n".join(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
