#!/usr/bin/env python3
# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# Resolves the Kconfig tree and writes what the build reads.
#
#   in :  Kconfig tree + a BASE (the live .config if there is one, else the board's
#         defconfig) + CONFIG_x=y overrides
#   out:  <gen>/.config                            the resolved configuration
#         <gen>/include/kickos/board_config.h       the C-visible knobs
#         <gen>/kickos_config.cmake                 the build-graph facts
#
# Running kconfiglib is not by itself the scheme: kconfiglib WARNS and falls back on
# a symbol's default for an out-of-range int, and drops an assignment whose
# dependencies are unmet. check_assignments reads every requested value back and
# refuses a mismatch, so a board asking for what it cannot have fails here instead
# of building with a value nobody chose.

import os
import sys

import kconfiglib

# Which knobs cross either boundary is a RULE, not a list: every symbol named KICKOS_*, in
# declaration order. The names are the ones the tree uses, not CONFIG_-prefixed.
#
# The HEADER takes the numeric ones only. A bool emitted there as 0/1 would turn on every
# `#if defined(KICKOS_ENABLE_SELFTEST)` site, that knob being defined only when it is on,
# so a knob C reads with `#if` is declared `int` with `range 0 1`.
KNOB_PREFIX = "KICKOS_"
C_KNOB_TYPES = (kconfiglib.INT, kconfiglib.HEX)

# CMake's own false constants, matching `if(<variable>)`: anything else is true, an arbitrary
# word included. This is how a candidate's value becomes y or n for a bool symbol.
CMAKE_FALSE = ("", "0", "OFF", "NO", "FALSE", "N", "IGNORE", "NOTFOUND")


def sym_int(kconf, name):
    sym = kconf.syms.get(name)
    if sym is None:
        return None
    value = sym.str_value
    if value == "":
        return None
    return int(value, 0)


def sym_str(kconf, name):
    sym = kconf.syms.get(name)
    if sym is None:
        return ""
    return sym.str_value


def sym_help(sym):
    for node in sym.nodes:
        if node.help:
            return "\n    " + node.help.replace("\n", "\n    ")
    return ""


def write_board_config(path, kconf):
    lines = [
        "/* SPDX-License-Identifier: CECILL-C */",
        "/* GENERATED by tools/kconfig/genconfig.py. Edits are overwritten. */",
        "/* Pure integer macros only: also included from startup.S. */",
        "",
        "#ifndef KICKOS_BOARD_CONFIG_H",
        "#define KICKOS_BOARD_CONFIG_H",
        "",
    ]
    # #ifndef and not a bare #define: a knob whose -D forwarding is still in place
    # would otherwise be a -Werror redefinition. The guard goes inert when that -D
    # is deleted, which must happen in the same step the knob lands here.
    for sym in kconf.unique_defined_syms:
        if not sym.name.startswith(KNOB_PREFIX):
            continue
        if sym.type not in C_KNOB_TYPES:
            continue
        # Empty when the symbol's dependencies are unmet, so it is not offered on this
        # board and C keeps its own default.
        if sym.str_value == "":
            continue
        # str_value, not an int: it already carries the declared form, so a hex knob
        # stays hexadecimal and reads like the register address it is.
        lines.append("#ifndef " + sym.name)
        lines.append("#define " + sym.name + " " + sym.str_value)
        lines.append("#endif")
    lines.append("")
    lines.append("#endif /* KICKOS_BOARD_CONFIG_H */")
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def cmake_escape(value):
    # A quoted set() argument still expands ${...}/$ENV{...}, still ends on an
    # unescaped quote, and still splits on an unescaped semicolon (CMake has no
    # string type distinct from a list), so all three need a backslash, and the
    # backslash itself must be escaped first or it can eat the character after it.
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("$", "\\$")
    value = value.replace(";", "\\;")
    return value


def cmake_knob(sym):
    if sym.type == kconfiglib.STRING:
        return '"' + cmake_escape(sym.str_value) + '"'
    if sym.type in C_KNOB_TYPES:
        # Empty when the dependencies are unmet, and CMake has no #ifndef fallback for it
        # the way the header has: an unset variable and an empty one read alike in if(),
        # math() refuses an empty expression, and add_compile_definitions(X=${X}) would
        # emit a bare `X=` that satisfies #if defined at every site. Zero is what every
        # reader here already spells "not on this board".
        if sym.str_value == "":
            return "0"
        # Decimal even for a hex knob, so a value CMake compares with EQUAL or feeds to
        # math() carries no base prefix.
        return str(int(sym.str_value, 0))
    if sym.str_value == "y":
        return "ON"
    return "OFF"


def prompted(sym):
    for node in sym.nodes:
        if node.prompt:
            return True
    return False


def write_cmake_fragment(path, kconf, sources, base):
    lines = ["# GENERATED by tools/kconfig/genconfig.py. Edits are overwritten.",
             # Which file this resolution was based on: a live .config outranks the
             # defconfig, so an in-place defconfig edit does not reach an existing build.
             'set(KICKOS_KCONFIG_BASE "' + cmake_escape(base) + '")']
    # Beside the values, which of the names a -D can move, split by request syntax. The AMP
    # peer seed reads both: it hands a peer every knob this node resolved, and a bool ABSENT
    # from a .config is off rather than unstated, so one loop cannot seed both.
    values = []
    flags = []
    for sym in kconf.unique_defined_syms:
        if not sym.name.startswith(KNOB_PREFIX):
            continue
        lines.append("set(" + sym.name + " " + cmake_knob(sym) + ")")
        if not prompted(sym) or sym.choice is not None:
            continue
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            flags.append(sym.name)
        else:
            values.append(sym.name)
    lines.append('set(KICKOS_KCONFIG_PROMPTED_VALUE "' + ";".join(values) + '")')
    lines.append('set(KICKOS_KCONFIG_PROMPTED_FLAG "' + ";".join(flags) + '")')
    # Every declaration file that was read, absolute. CMake re-runs configure when one
    # changes and takes the list from here, so it never learns which Kconfig files
    # exist. The override fragment is excluded: it lives in the build tree and is
    # rewritten every configure.
    inputs = []
    for name in list(kconf.kconfig_filenames) + list(sources):
        inputs.append(cmake_escape(os.path.abspath(name)))
    lines.append('set(KICKOS_KCONFIG_SOURCES "' + ";".join(inputs) + '")')
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def requested_assignments(paths):
    wanted = []
    for path in paths:
        with open(path) as handle:
            for line in handle:
                line = line.strip()
                if not line.startswith("CONFIG_"):
                    continue
                if "=" not in line:
                    continue
                name, value = line[len("CONFIG_"):].split("=", 1)
                wanted.append((name, value))
    return wanted


def candidate_request(kconf, name, value):
    # One of the two is empty: a CONFIG_ line the loader can take, or why no request could
    # be built from this name.
    sym = kconf.syms.get(name)
    if sym is None:
        return ("", "no such symbol")
    if not prompted(sym):
        return ("", "no prompt, so nothing can set it: it is derived, not configuration")
    if sym.choice is not None:
        return ("", "a member of a choice: a variant defconfig selects one, and no -D of a "
                    "member's own name reaches it")
    if sym.type == kconfiglib.STRING:
        # kconfiglib's own quoting, which cares about a backslash and a quote and nothing
        # else. check_assignments strips the quotes back off to compare.
        quoted = value.replace("\\", "\\\\").replace('"', '\\"')
        return ("CONFIG_" + name + '="' + quoted + '"', "")
    if sym.type in C_KNOB_TYPES:
        return ("CONFIG_" + name + "=" + value, "")
    # BOTH DIRECTIONS: a candidate resolved off must travel as `n`, or a defconfig that
    # enables something outranks a command line asking to turn it off.
    flag = "y"
    upper = value.upper()
    if upper in CMAKE_FALSE or upper.endswith("-NOTFOUND"):
        flag = "n"
    return ("CONFIG_" + name + "=" + flag, "")


def check_assignments(kconf, wanted):
    # Only the LAST assignment of each symbol is checked: a later fragment REPLACES
    # an earlier one, and a choice sibling turning its siblings off is the mechanism
    # working rather than a conflict.
    last = {}
    for name, value in wanted:
        last[name] = value

    displaced = set()
    for name in last:
        sym = kconf.syms.get(name)
        if sym is None or sym.choice is None:
            continue
        if last[name] != "y":
            continue
        for sibling in sym.choice.syms:
            if sibling.name != name:
                displaced.add(sibling.name)

    refused = []
    for name in sorted(last):
        value = last[name]
        if name in displaced:
            continue
        sym = kconf.syms.get(name)
        if sym is None:
            refused.append((name, value, "no such symbol"))
            continue
        got = sym.str_value
        if got == value.strip('"'):
            continue
        if not prompted(sym):
            # kconfiglib drops a user value on a promptless symbol and says nothing, so
            # without this arm the refusal below would blame the symbol's dependency,
            # which for every promptless symbol in this tree is `y`.
            reason = ("no prompt, so nothing can set it: it is derived, not "
                      "configuration")
        elif sym.type in (kconfiglib.INT, kconfiglib.HEX) and sym.ranges:
            low, high, _cond = sym.ranges[0]
            reason = ("outside the declared range [" + low.str_value + ", " +
                      high.str_value + "]")
        else:
            reason = "unmet dependency: " + kconfiglib.expr_str(sym.direct_dep)
        reason = reason + ": resolved to '" + got + "'"
        # The declaration's own help, so a refusal explains itself instead of leaving a
        # hand-written hint to be maintained somewhere else and go stale.
        reason = reason + sym_help(sym)
        refused.append((name, value, reason))
    return refused


def main(argv):
    if len(argv) < 4:
        sys.stderr.write("usage: genconfig.py <srcdir> <defconfig> <gendir> "
                         "[CONFIG_X=y | offer:X=v | assert:X=v ...]\n")
        return 2
    srcdir, defconfig, gendir = argv[1], argv[2], argv[3]
    requests = argv[4:]

    defconfig = os.path.abspath(defconfig)
    gendir = os.path.abspath(gendir)
    os.chdir(srcdir)

    # Two ROLES, not two homes for one value. The defconfig is the saved, reviewable,
    # git-stored starting point; <gen>/.config is the LIVE state this build is based on.
    # So the defconfig seeds the first configure and .config is authoritative after
    # that, exactly as a preset's cacheVariables seed CMakeCache.txt once and the cache
    # rules afterwards. Editing a defconfig therefore does NOT reach an existing build
    # dir until it is reloaded, which is the same contract CMake already has.
    live = os.path.join(gendir, ".config")
    stamp = os.path.join(gendir, ".defconfig")
    base = defconfig
    if os.path.exists(live):
        base = live
        # Which defconfig the live state came from. Selecting another variant in an
        # EXISTING build directory would otherwise be dropped in silence: the live
        # .config is the base, so the newly named defconfig is never read, and board,
        # arch, family and chip all still agree so no other check notices. Refusing is
        # the answer rather than reloading, because reloading discards whatever
        # menuconfig has accumulated here.
        previous = ""
        if os.path.exists(stamp):
            previous = open(stamp).read().strip()
        if previous != "" and previous != defconfig:
            sys.stderr.write(
                "REFUSED variant change: this build directory is configured from\n"
                "  " + previous + "\nand the request names\n  " + defconfig + "\n"
                "The live " + live + " is the state this build is based on, so the new "
                "defconfig would be read by nothing. Use a fresh build directory, or "
                "delete that .config to reload from the new variant.\n")
            return 1
    kconf = kconfiglib.Kconfig("Kconfig", warn_to_stderr=True)

    # THREE REQUEST SHAPES, and only the first is stated in Kconfig's own syntax:
    #
    #   CONFIG_<name>=<value>   a request, honoured or refused as written
    #   offer:<NAME>=<value>    a CMake variable whose name MIGHT be a knob
    #   assert:<NAME>=<value>   the same, and only a command line or a preset can have
    #                           made it: it is an UNINITIALIZED cache entry, so no
    #                           declaration in the build owns the name
    #
    # CMake cannot tell a knob from its own variables, the KICKOS_* space also carrying the
    # board identity, the build-graph switches and the per-board link knobs, so it offers
    # every one of them and the declarations decide here. An offer the declarations cannot
    # take is DROPPED, so a promptless symbol stays unreachable by any -D. An ASSERTED one
    # naming a symbol no request can reach is refused instead, since nothing but the request
    # itself put that name there.
    overrides = []
    for request in requests:
        # The shape FIRST, and a nameless one is refused rather than dropped: a request the
        # loader and the read-back check both skip would otherwise look honoured.
        shape = ""
        for prefix in ("CONFIG_", "offer:", "assert:"):
            if request.startswith(prefix) and "=" in request:
                shape = prefix
        name = ""
        value = ""
        if shape != "":
            name, value = request[len(shape):].split("=", 1)
        if name == "":
            sys.stderr.write("REFUSED request '" + request + "': not of the form "
                             "CONFIG_<name>=<value>, offer:<NAME>=<value> or "
                             "assert:<NAME>=<value>\n")
            return 1
        if shape == "CONFIG_":
            overrides.append(request)
            continue
        built, why = candidate_request(kconf, name, value)
        if built != "":
            overrides.append(built)
            continue
        if shape == "offer:":
            continue
        if why == "no such symbol":
            # The KICKOS_ namespace is wider than Kconfig: a build-graph switch or a
            # per-board link knob is declared in CMake alone and appears in no .config.
            # Dropping it here leaves CMake's own "manually-specified variables were not
            # used" notice to report a name that is neither.
            continue
        sys.stderr.write("REFUSED -D" + name + "=" + value + ": " + why + "\n")
        return 1

    print(kconf.load_config(base))

    # Every symbol the loaded BASE named that the tree does not declare; the override
    # fragment is loaded further down, so nothing here came from a -D. kconfiglib does not
    # warn on one by default (warn_assign_undef is off), and a hand-edited live .config is
    # not read back as a set of requests, so a typo there would otherwise land nowhere at
    # all and say nothing.
    if kconf.missing_syms:
        for name, value in kconf.missing_syms:
            sys.stderr.write("REFUSED CONFIG_" + name + "=" + value
                             + ": no such symbol\n")
        # ONLY where the base was the live state: a defconfig naming a symbol the tree does
        # not declare is an edit to fix, while a .config carrying one is a directory the tree
        # moved past.
        if base != defconfig:
            sys.stderr.write(
                "The live " + live + " is the state this build is based on, and the tree "
                "no longer declares that symbol. Use a fresh build directory, or delete "
                "that .config to reload from " + defconfig + ".\n")
        return 1

    # Only the DEFCONFIG's lines are read back as requests. A live .config is state, not
    # a set of requests: every symbol in it is an explicit value, so checking them would
    # report the resolution disagreeing with itself.
    sources = []
    if base == defconfig:
        sources.append(defconfig)
    if overrides:
        # The loader keeps the LAST assignment of a symbol, so a name given twice makes
        # which request is honoured depend on argument order. The warning that would say so
        # is turned off below; this replaces it.
        seen = {}
        for override in overrides:
            name = override[len("CONFIG_"):].split("=", 1)[0]
            if name in seen:
                sys.stderr.write("REFUSED override '" + override + "': CONFIG_" + name
                                 + " is requested twice, already as '" + seen[name]
                                 + "'\n")
                return 1
            seen[name] = override
        os.makedirs(gendir, exist_ok=True)
        fragment = os.path.join(gendir, "override.config")
        with open(fragment, "w") as handle:
            handle.write("\n".join(overrides) + "\n")
        # After the first configure the base is the live .config, in which every forwarded
        # knob carries an explicit value, so a request repeating that value is redundant
        # rather than a finding. CMakeLists escalates any warning from here to a CMake
        # WARNING, which would put a spurious one on every re-configure. A request naming a
        # DIFFERENT value still warns.
        kconf.warn_assign_redun = False
        try:
            print(kconf.load_config(fragment, replace=False))
        finally:
            kconf.warn_assign_redun = True
        sources.append(fragment)

    refused = check_assignments(kconf, requested_assignments(sources))
    if refused:
        for name, value, reason in refused:
            sys.stderr.write("REFUSED CONFIG_" + name + "=" + value + ": " +
                             reason + "\n")
        return 1

    os.makedirs(os.path.join(gendir, "include", "kickos"), exist_ok=True)
    kconf.write_config(os.path.join(gendir, ".config"))
    with open(stamp, "w") as handle:
        handle.write(defconfig + "\n")
    write_board_config(
        os.path.join(gendir, "include", "kickos", "board_config.h"), kconf)
    write_cmake_fragment(os.path.join(gendir, "kickos_config.cmake"), kconf,
                         [defconfig], base)

    print("board=" + sym_str(kconf, "KICKOS_BOARD") +
          " arch=" + sym_str(kconf, "KICKOS_ARCH") +
          " chip=" + sym_str(kconf, "KICKOS_CHIP") +
          " mpu=" + str(sym_int(kconf, "KICKOS_HAVE_MPU")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
