#!/usr/bin/env python3
# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# Resolves the Kconfig tree and writes what the build reads.
#
#   in :  Kconfig tree + a BASE (the live .config if there is one, else the board's
#         defconfig) + CONFIG_x=y overrides
#   out:  <gen>/.config                            the resolved configuration
#         <gen>/include/kickos/board_config.h       the C-visible knobs
#         <gen>/kickos_config.cmake                 the build-graph facts
#
# Running kconfiglib is not by itself the scheme: kconfiglib WARNS and falls back on
# a symbol's default for an out-of-range int, and drops an assignment whose
# dependencies are unmet. check_assignments reads every requested value back and
# refuses a mismatch, so a board asking for what it cannot have fails here instead
# of building with a value nobody chose.

import os
import sys

import kconfiglib

# Which knobs reach C is a RULE, not a list: every numeric symbol named KICKOS_*, in
# declaration order. With a hand-maintained list a knob can be declared, set in a
# defconfig, resolved into .config, and then silently never reach the compile.
# Over-emitting is harmless while a knob still arrives as a -D, since the header's define
# is #ifndef-guarded and the -D wins; under-emitting is a defect. The names are the ones
# the tree uses, not CONFIG_-prefixed.
C_KNOB_PREFIX = "KICKOS_"
C_KNOB_TYPES = (kconfiglib.INT, kconfiglib.HEX)

# What CMake reads. A value CMake can derive for itself (the console 0/1 pair from the
# console string) is deliberately absent, so no fact is computed twice.
CMAKE_STRING_KNOBS = [
    "KICKOS_BOARD",
    "KICKOS_ARCH",
    "KICKOS_ARCH_FAMILY",
    "KICKOS_CHIP",
    "KICKOS_CONSOLE",
    "KICKOS_TELEMETRY",
    "KICKOS_SERVICE_LIST",
    "KICKOS_BOARD_PINMAP",
]
# The provisioning integers CMake itself has to do arithmetic on: the capability-table
# sum (cmake/cap_table.cmake) and the boot-arena model (cmake/boot_arena.cmake). A knob
# CMake computes with belongs here; one only C reads does not.
CMAKE_INT_KNOBS = [
    "KICKOS_HAVE_MPU",
    "KICKOS_TRACE_CLOCK_DECLARED",
    "KICKOS_MIN_STACK_SIZE",
    "KICKOS_USER_HEAP_SIZE",
    "KICKOS_MAX_THREADS",
    "KICKOS_MAX_SPAWN_GRANTS",
    "KICKOS_CAP_TABLE_SUPPLY",
    "KICKOS_IDLE_STACK_SIZE",
    "KICKOS_ROOT_STACK_SIZE",
    "KICKOS_USER_STACK_SIZE",
]
# CMake variable name -> Kconfig symbol. These reach C through an unconditional
# add_compile_definitions rather than through the #ifndef header, so CMake must take
# them from here: option() would otherwise win and a defconfig setting one would be
# describing a build nobody made.
CMAKE_BOOL_KNOBS = {
    "KICKOS_DEBUG": "KICKOS_DEBUG",
    "KICKOS_ENABLE_SELFTEST": "KICKOS_ENABLE_SELFTEST",
    "KICKOS_BENCH": "KICKOS_BENCH",
    "KICKOS_SHUTDOWN_TO_BOOTLOADER": "KICKOS_SHUTDOWN_TO_BOOTLOADER",
    "KICKOS_TIMED_WAIT": "KICKOS_TIMED_WAIT",
    "CONFIG_SCHED_PERIODIC_TICK": "SCHED_PERIODIC_TICK",
}


def sym_int(kconf, name):
    sym = kconf.syms.get(name)
    if sym is None:
        return None
    value = sym.str_value
    if value == "":
        return None
    return int(value, 0)


def sym_bool(kconf, name):
    sym = kconf.syms.get(name)
    if sym is None:
        return False
    return sym.str_value == "y"


def sym_str(kconf, name):
    sym = kconf.syms.get(name)
    if sym is None:
        return ""
    return sym.str_value


def sym_help(sym):
    for node in sym.nodes:
        if node.help:
            return "\n    " + node.help.replace("\n", "\n    ")
    return ""


def write_board_config(path, kconf):
    lines = [
        "/* SPDX-License-Identifier: CECILL-C */",
        "/* GENERATED by tools/kconfig/genconfig.py. Edits are overwritten. */",
        "/* Pure integer macros only: also included from startup.S. */",
        "",
        "#ifndef KICKOS_BOARD_CONFIG_H",
        "#define KICKOS_BOARD_CONFIG_H",
        "",
    ]
    # #ifndef and not a bare #define: a knob whose -D forwarding is still in place
    # would otherwise be a -Werror redefinition. The guard goes inert when that -D
    # is deleted, which must happen in the same step the knob lands here.
    for sym in kconf.unique_defined_syms:
        if not sym.name.startswith(C_KNOB_PREFIX):
            continue
        if sym.type not in C_KNOB_TYPES:
            continue
        # Empty when the symbol's dependencies are unmet, so it is not offered on this
        # board and C keeps its own default.
        if sym.str_value == "":
            continue
        # str_value, not an int: it already carries the declared form, so a hex knob
        # stays hexadecimal and reads like the register address it is.
        lines.append("#ifndef " + sym.name)
        lines.append("#define " + sym.name + " " + sym.str_value)
        lines.append("#endif")
    lines.append("")
    lines.append("#endif /* KICKOS_BOARD_CONFIG_H */")
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def write_cmake_fragment(path, kconf, sources):
    lines = ["# GENERATED by tools/kconfig/genconfig.py. Edits are overwritten."]
    for name in CMAKE_STRING_KNOBS:
        lines.append('set(' + name + ' "' + sym_str(kconf, name) + '")')
    for name in CMAKE_INT_KNOBS:
        value = sym_int(kconf, name)
        if value is None:
            value = 0
        lines.append("set(" + name + " " + str(value) + ")")
    for name in sorted(CMAKE_BOOL_KNOBS):
        value = "OFF"
        if sym_bool(kconf, CMAKE_BOOL_KNOBS[name]):
            value = "ON"
        lines.append("set(" + name + " " + value + ")")
    # Every declaration file that was read, absolute. CMake re-runs configure when one
    # changes and takes the list from here, so it never learns which Kconfig files
    # exist. The override fragment is excluded: it lives in the build tree and is
    # rewritten every configure.
    inputs = []
    for name in list(kconf.kconfig_filenames) + list(sources):
        inputs.append(os.path.abspath(name))
    lines.append('set(KICKOS_KCONFIG_SOURCES "' + ";".join(inputs) + '")')
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def requested_assignments(paths):
    wanted = []
    for path in paths:
        with open(path) as handle:
            for line in handle:
                line = line.strip()
                if not line.startswith("CONFIG_"):
                    continue
                if "=" not in line:
                    continue
                name, value = line[len("CONFIG_"):].split("=", 1)
                wanted.append((name, value))
    return wanted


def check_assignments(kconf, wanted):
    # Only the LAST assignment of each symbol is checked: a later fragment REPLACES
    # an earlier one, and a choice sibling turning its siblings off is the mechanism
    # working rather than a conflict.
    last = {}
    for name, value in wanted:
        last[name] = value

    displaced = set()
    for name in last:
        sym = kconf.syms.get(name)
        if sym is None or sym.choice is None:
            continue
        if last[name] != "y":
            continue
        for sibling in sym.choice.syms:
            if sibling.name != name:
                displaced.add(sibling.name)

    refused = []
    for name in sorted(last):
        value = last[name]
        if name in displaced:
            continue
        sym = kconf.syms.get(name)
        if sym is None:
            refused.append((name, value, "no such symbol"))
            continue
        got = sym.str_value
        if got == value.strip('"'):
            continue
        prompted = False
        for node in sym.nodes:
            if node.prompt:
                prompted = True
        if not prompted:
            # kconfiglib drops a user value on a promptless symbol and says nothing, so
            # without this arm the refusal below would blame the symbol's dependency,
            # which for every promptless symbol in this tree is `y`.
            reason = ("no prompt, so nothing can set it: it is derived, not "
                      "configuration")
        elif sym.type in (kconfiglib.INT, kconfiglib.HEX) and sym.ranges:
            low, high, _cond = sym.ranges[0]
            reason = ("outside the declared range [" + low.str_value + ", " +
                      high.str_value + "]")
        else:
            reason = "unmet dependency: " + kconfiglib.expr_str(sym.direct_dep)
        reason = reason + " -- resolved to '" + got + "'"
        # The declaration's own help, so a refusal explains itself instead of leaving a
        # hand-written hint to be maintained somewhere else and go stale.
        reason = reason + sym_help(sym)
        refused.append((name, value, reason))
    return refused


def main(argv):
    if len(argv) < 4:
        sys.stderr.write("usage: genconfig.py <srcdir> <defconfig> <gendir> "
                         "[CONFIG_X=y ...]\n")
        return 2
    srcdir, defconfig, gendir = argv[1], argv[2], argv[3]
    overrides = argv[4:]

    defconfig = os.path.abspath(defconfig)
    gendir = os.path.abspath(gendir)
    os.chdir(srcdir)

    # Two ROLES, not two homes for one value. The defconfig is the saved, reviewable,
    # git-stored starting point; <gen>/.config is the LIVE state this build is based on.
    # So the defconfig seeds the first configure and .config is authoritative after
    # that, exactly as a preset's cacheVariables seed CMakeCache.txt once and the cache
    # rules afterwards. Editing a defconfig therefore does NOT reach an existing build
    # dir until it is reloaded, which is the same contract CMake already has.
    live = os.path.join(gendir, ".config")
    stamp = os.path.join(gendir, ".defconfig")
    base = defconfig
    if os.path.exists(live):
        base = live
        # Which defconfig the live state came from. Selecting another variant in an
        # EXISTING build directory would otherwise be dropped in silence: the live
        # .config is the base, so the newly named defconfig is never read, and board,
        # arch, family and chip all still agree so no other check notices. Refusing is
        # the answer rather than reloading, because reloading discards whatever
        # menuconfig has accumulated here.
        previous = ""
        if os.path.exists(stamp):
            previous = open(stamp).read().strip()
        if previous != "" and previous != defconfig:
            sys.stderr.write(
                "REFUSED variant change: this build directory is configured from\n"
                "  " + previous + "\nand the request names\n  " + defconfig + "\n"
                "The live " + live + " is the state this build is based on, so the new "
                "defconfig would be read by nothing. Use a fresh build directory, or "
                "delete that .config to reload from the new variant.\n")
            return 1
    kconf = kconfiglib.Kconfig("Kconfig", warn_to_stderr=True)
    print(kconf.load_config(base))

    # Every symbol a defconfig or an override NAMED that the tree does not declare.
    # kconfiglib does not warn on one by default (warn_assign_undef is off), and a
    # hand-edited live .config is not read back as a set of requests, so a typo there
    # would otherwise land nowhere at all and say nothing.
    if kconf.missing_syms:
        for name, value in kconf.missing_syms:
            sys.stderr.write("REFUSED CONFIG_" + name + "=" + value
                             + ": no such symbol\n")
        return 1

    # Only the DEFCONFIG's lines are read back as requests. A live .config is state, not
    # a set of requests: every symbol in it is an explicit value, so checking them would
    # report the resolution disagreeing with itself.
    sources = []
    if base == defconfig:
        sources.append(defconfig)
    if overrides:
        # An override that is not CONFIG_<name>=<value> is dropped by the loader AND
        # by the read-back check, which together would make a typo'd knob look
        # honoured. Refuse the shape here, where it is the caller's own argument.
        for override in overrides:
            name = ""
            if override.startswith("CONFIG_") and "=" in override:
                name = override[len("CONFIG_"):].split("=", 1)[0]
            if name == "":
                sys.stderr.write("REFUSED override '" + override + "': not of the "
                                 "form CONFIG_<name>=<value>\n")
                return 1
        os.makedirs(gendir, exist_ok=True)
        fragment = os.path.join(gendir, "override.config")
        with open(fragment, "w") as handle:
            handle.write("\n".join(overrides) + "\n")
        print(kconf.load_config(fragment, replace=False))
        sources.append(fragment)

    refused = check_assignments(kconf, requested_assignments(sources))
    if refused:
        for name, value, reason in refused:
            sys.stderr.write("REFUSED CONFIG_" + name + "=" + value + ": " +
                             reason + "\n")
        return 1

    os.makedirs(os.path.join(gendir, "include", "kickos"), exist_ok=True)
    kconf.write_config(os.path.join(gendir, ".config"))
    with open(stamp, "w") as handle:
        handle.write(defconfig + "\n")
    write_board_config(
        os.path.join(gendir, "include", "kickos", "board_config.h"), kconf)
    write_cmake_fragment(os.path.join(gendir, "kickos_config.cmake"), kconf,
                         [defconfig])

    print("board=" + sym_str(kconf, "KICKOS_BOARD") +
          " arch=" + sym_str(kconf, "KICKOS_ARCH") +
          " chip=" + sym_str(kconf, "KICKOS_CHIP") +
          " mpu=" + str(sym_int(kconf, "KICKOS_HAVE_MPU")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
