# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc

import contextlib
import io
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

from kickos_compose import chip
from kickos_compose.__main__ import main
from kickos_compose.subset import Report

TREE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
PLATFORM = os.path.join(TREE, "platform")
COMPOSE = os.path.join(TREE, "tools", "compose")
COMPILER = [shutil.which("g++") or "g++"]
# The arch each described chip builds for, and on a multi-architecture part the one cluster it picks.
ARCHES = {
    "xmc4800": "armv7m", "stm32f411": "armv7m", "mk64f": "armv7m", "esp32c6": "rv32imac", "virt_rv32": "rv32imac",
    "virt_arm64": "armv8a", "virt_rv64": "rv64imac", "q35": "x86_64", "imx8mp": "armv8a", "stm32f103": "armv7m",
    "stm32f302": "armv7m", "rp2040": "armv6m", "rp2350": "armv7m", "imxrt1062": "armv7m",
    "sam3x8e": "armv7m", "nrf51": "armv6m", "mps2": "armv7m", "an505": "armv7m", "rx72m": "rxv3",
    "esp32": "lx6", "sim": "sim",
}

SMALL = """version: 1
chip: small
manual: "The Small Part Manual, rev 2"
arch: armv7m
protection: { unit: pmsav7, covers_devices: true, memory_type: true }
interrupts: { count: { value: 40, ref: "Table 1, p.3" }, free_from: 30 }
cycle_counter: { hz: 0, glitches: true }
c: { namespace: kickos::sm, line_enum: "node : int" }
devices:
  uart: { window: [0x40001000, 0x100], ref: "p.10", lines: { rx: 5, tx: { number: 6, ref: "p.11", symbol: UART_TX_IRQ } } }
  port: { window: [0x40002000, 0x100], count: 3, stride: 0x100, symbol: PORTA_BASE }
  gap: { window: [0x40010000, 0x100], count: 2, stride: 0x400 }
  usic: { channels: { ch0: { window: [0x40020000, 0x200] }, ch1: { window: [0x40020200, 0x200], symbol: U0C1 } } }
  scu: { window: [0x50000000, 0x4000], owner: kernel, blocks: { trap: 0x160, pll: { offset: 0x710, symbol: PLL_REGS } } }
  timer: { window: [0x50010000, 0x1000], owner: kernel, lines: { tick: 7 } }
memory:
  flash: { base: 0x08000000, size: 0x200000, symbol: FLASH_CACHED_BASE, link: { region: FLASH, access: rx } }
  sram: { base: 0x20000000, size: 0x20000, arena: true, link: { region: RAM, access: rwx } }
"""

HAND_MMAP = """#include <stdint.h>
namespace kickos::sm::mmap
{
    constexpr uintptr_t UART_BASE = 0x40001000u;
    constexpr uintptr_t PORTA_BASE = 0x40002000u;
    constexpr uintptr_t PORT_STRIDE = 0x100u;
    constexpr uintptr_t SCU_TRAP_BASE = 0x50000160u;
    constexpr uintptr_t PLL_REGS = 0x50000710u;
}
"""

HAND_IRQ = """namespace kickos::sm::irq
{
    enum node : int
    {
        UART_RX = 5,
        UART_TX_IRQ = 6,
    };
}
"""

HAND_LIMITS = """#define KICKOS_MAX_IRQ 40
#define KICKOS_IRQ_FREE_BASE 30
#define KICKOS_CHIP_CYCCNT_HZ 0
#define KICKOS_CHIP_CYCCNT_GLITCHES 1
"""


class Generated(unittest.TestCase):
    def setUp(self):
        self.scratch = tempfile.mkdtemp(prefix="kickos-chip-")
        self.platform = os.path.join(self.scratch, "platform", "small")
        os.makedirs(self.platform)
        self.path = os.path.join(self.platform, "chip.yaml")
        self.write(self.path, SMALL)

    def tearDown(self):
        shutil.rmtree(self.scratch)

    def write(self, path, text):
        with open(path, "w", encoding="ascii") as stream:
            stream.write(text)

    def view(self, path=None, arch="armv7m"):
        report = Report()
        described, board = chip.read(path or self.path, report)
        self.assertEqual([str(r) for r in report.refusals], [])
        return chip.view_of(described, arch, board)

    def header(self, name, text):
        path = os.path.join(self.scratch, "hand", name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        self.write(path, text)
        return path

    def compare(self, name, text):
        return chip.compare(self.view(), self.header(name, text), COMPILER)

    def test_mmap_names_values_and_refs(self):
        text = chip.generate(self.view())["chip_mmap.h"]
        self.assertTrue(text.startswith("// Generated by kickos_compose chip from platform/small/chip.yaml\n"
                                        "// The Small Part Manual, rev 2\n"))
        for line in ("namespace kickos::sm::mmap", "constexpr uintptr_t UART_BASE = 0x40001000u; // p.10",
                     "PORTA_BASE = 0x40002000u;", "PORT_STRIDE = 0x100u;", "GAP0_BASE = 0x40010000u;",
                     "USIC_CH0_BASE = 0x40020000u;", "U0C1 = 0x40020200u;", "SCU_TRAP_BASE = 0x50000160u;",
                     "PLL_REGS = 0x50000710u;", "FLASH_CACHED_BASE = 0x8000000u;", "SRAM_BASE = 0x20000000u;"):
            self.assertIn(line, text)

    def test_irq_limits_layout(self):
        outputs = chip.generate(self.view())
        self.assertIn("    enum node : int\n", outputs["irq.h"])
        self.assertIn("UART_TX_IRQ = 6, // p.11", outputs["irq.h"])
        self.assertIn("TIMER_TICK = 7,", outputs["irq.h"])
        self.assertIn("#ifndef KICKOS_ARCH_ARM_CHIP_SMALL_IRQ_H", outputs["irq.h"])
        self.assertIn("#define KICKOS_MAX_IRQ 40 /* Table 1, p.3 */", outputs["chip_limits.h"])
        self.assertIn("#define KICKOS_IRQ_FREE_BASE 30", outputs["chip_limits.h"])
        self.assertIn("#define KICKOS_CHIP_CYCCNT_HZ 0", outputs["chip_limits.h"])
        self.assertIn("#define KICKOS_CHIP_CYCCNT_GLITCHES 1", outputs["chip_limits.h"])
        self.assertIn("#define KICKOS_LINK_FLASH FLASH (rx) : ORIGIN = 0x8000000, LENGTH = 0x200000", outputs["chip_layout.h"])
        self.assertIn("#define KICKOS_LAYOUT_SRAM_SIZE 0x20000", outputs["chip_layout.h"])
        self.assertIn("#define KICKOS_LAYOUT_SCU_SIZE 0x4000", outputs["chip_layout.h"])
        self.assertIn("#define KICKOS_LAYOUT_PORT_SIZE 0x100", outputs["chip_layout.h"])
        self.assertIn("#define KICKOS_LAYOUT_LINE_UART_TX_IRQ 6 /* p.11 */", outputs["chip_layout.h"])
        self.assertIn("#define KICKOS_LAYOUT_LINE_TIMER_TICK 7\n", outputs["chip_layout.h"])
        self.assertIn("\nset(KICKOS_CHIP_LINK_FLASH_ORIGIN 0x8000000)\nset(KICKOS_CHIP_LINK_FLASH_LENGTH 0x200000)\n"
                      "set(KICKOS_CHIP_LINK_RAM_ORIGIN 0x20000000)\nset(KICKOS_CHIP_LINK_RAM_LENGTH 0x20000)\n",
                      outputs["chip.cmake"])
        self.assertTrue(outputs["chip.cmake"].endswith(
            "\nset(KICKOS_CHIP_REGION_UNIT \"pmsav7\")\nset(KICKOS_CHIP_TRANSLATES OFF)\n"))
        for name, text in outputs.items():
            self.assertIn("Generated by kickos_compose chip from platform/small/chip.yaml", text.splitlines()[0], name)

    def test_tables_follow_ownership(self):
        rows = chip.table_rows(self.view())
        self.assertEqual([(b, s) for b, s, r in rows["reserved_blocks"]], [(0x50000000, 0x4000), (0x50010000, 0x1000)])
        self.assertEqual(rows["window_apertures"], [])
        self.assertEqual(rows["port_apertures"], [])

    def test_translating_apertures_and_ports(self):
        rows = chip.table_rows(self.view(os.path.join(PLATFORM, "q35", "chip.yaml"), "x86_64"))
        self.assertEqual([(b, s) for b, s, r in rows["reserved_blocks"]], [(0xFEE00000, 0x1000), (0xFEC00000, 0x1000)])
        self.assertEqual([(b, s) for b, s, r in rows["window_apertures"]], [(0xFED00000, 0x1000)])
        self.assertEqual([(b, s) for b, s, r in rows["port_apertures"]], [(0x70, 2), (0x3F8, 8), (0x2F8, 8)])

    def test_repeats_touching_are_one_row(self):
        text = SMALL.replace("  gap: { window: [0x40010000, 0x100], count: 2, stride: 0x400 }",
                             "  gap: { window: [0x40010000, 0x100], count: 2, stride: 0x400, owner: kernel }")
        text = text.replace("count: 3, stride: 0x100, symbol", "count: 3, stride: 0x100, owner: kernel, symbol")
        self.write(self.path, text)
        rows = [(b, s) for b, s, r in chip.table_rows(self.view())["reserved_blocks"]]
        self.assertEqual(rows[:3], [(0x40002000, 0x300), (0x40010000, 0x100), (0x40010400, 0x100)])

    def test_cluster_offset_and_choice(self):
        imx = os.path.join(PLATFORM, "imx8mp", "chip.yaml")
        a53 = chip.generate(self.view(imx, "armv8a"))
        m7 = chip.generate(self.view(imx, "armv7m"))
        self.assertIn("MU1_A_TO_A53 = 120,", a53["irq.h"])
        self.assertNotIn("MU1_B", a53["irq.h"])
        self.assertIn("MU1_B_TO_M7 = 97,", m7["irq.h"])
        self.assertIn("#define KICKOS_MAX_IRQ 192", a53["chip_limits.h"])
        self.assertIn("#define KICKOS_MAX_IRQ 160", m7["chip_limits.h"])
        self.assertIn("KICKOS_CHIP_TRANSLATES ON", a53["chip.cmake"])
        self.assertIn("KICKOS_CHIP_REGION_UNIT \"\")", m7["chip.cmake"])
        with self.assertRaises(chip.Failure):
            self.view(imx, "rv32imac")

    def test_every_described_chip_generates(self):
        for name, arch in sorted(ARCHES.items()):
            with self.subTest(chip=name):
                outputs = chip.generate(self.view(os.path.join(PLATFORM, name, "chip.yaml"), arch))
                self.assertEqual(sorted(outputs), sorted(chip.INCLUDE_OUTPUTS + chip.CHIP_OUTPUTS))

    def test_the_generated_headers_pass_their_own_compare(self):
        outputs = chip.generate(self.view())
        for name in ("chip_mmap.h", "irq.h", "chip_limits.h"):
            with self.subTest(header=name):
                self.assertEqual(self.compare(name, outputs[name]), None)

    def test_a_hand_header_agrees(self):
        self.assertEqual(self.compare("chip_mmap.h", HAND_MMAP), None)
        self.assertEqual(self.compare("irq.h", HAND_IRQ), None)
        self.assertEqual(self.compare("chip_limits.h", HAND_LIMITS), None)

    def test_a_planted_difference_shows(self):
        plants = [
            ("chip_mmap.h", HAND_MMAP, "UART_BASE = 0x40001000u", "UART_BASE = 0x40001004u"),
            ("chip_mmap.h", HAND_MMAP, "constexpr uintptr_t PORT_STRIDE", "constexpr uint32_t PORT_STRIDE"),
            ("chip_mmap.h", HAND_MMAP, "namespace kickos::sm::mmap", "namespace kickos::small::mmap"),
            ("irq.h", HAND_IRQ, "UART_RX = 5", "UART_RX = 4"),
            ("irq.h", HAND_IRQ, "enum node : int", "enum node : unsigned"),
            ("irq.h", HAND_IRQ, "enum node : int", "enum line : int"),
            ("chip_limits.h", HAND_LIMITS, "KICKOS_MAX_IRQ 40", "KICKOS_MAX_IRQ 41"),
            ("chip_limits.h", HAND_LIMITS, "#define KICKOS_IRQ_FREE_BASE 30\n", ""),
            ("chip_limits.h", HAND_LIMITS, "#define KICKOS_CHIP_CYCCNT_HZ 0\n", ""),
        ]
        for name, text, old, new in plants:
            with self.subTest(plant=new):
                self.assertNotEqual(self.compare(name, text.replace(old, new)), None)

    def test_a_header_sharing_nothing_is_refused(self):
        hand = self.header("chip_mmap.h", "#include <stdint.h>\nnamespace kickos::sm::mmap { constexpr uintptr_t X = 1; }\n")
        report, said, status = chip.run(self.path, "armv7m", header=hand, compiler=COMPILER)
        self.assertEqual(status, 1)
        self.assertIn("declares none", said[0])

    def test_the_cli_writes_only_what_changed(self):
        include = os.path.join(self.scratch, "out", "include")
        chip_dir = os.path.join(self.scratch, "out", "chip")
        arguments = ["chip", self.path, "--arch", "armv7m", "--include-dir", include, "--chip-dir", chip_dir]
        self.assertEqual(main(arguments), 0)
        mmap = os.path.join(include, "kickos", "chip_mmap.h")
        irq = os.path.join(chip_dir, "irq.h")
        os.utime(mmap, (1, 1))
        os.utime(irq, (1, 1))
        self.write(self.path, SMALL.replace("lines: { rx: 5,", "lines: { rx: 4,"))
        self.assertEqual(main(arguments), 0)
        self.assertEqual(os.stat(mmap).st_mtime, 1)
        self.assertNotEqual(os.stat(irq).st_mtime, 1)

    def test_a_refused_file_writes_nothing(self):
        self.write(self.path, SMALL.replace("count: { value: 40,", "count: { value: 4,"))
        out = os.path.join(self.scratch, "out")
        said = io.StringIO()
        with contextlib.redirect_stdout(said):
            status = main(["chip", self.path, "--arch", "armv7m", "--include-dir", out, "--chip-dir", out])
        self.assertEqual(status, 3)
        self.assertIn("chip.line-range", said.getvalue())
        self.assertFalse(os.path.exists(out))

    def test_the_cli_compares(self):
        hand = self.header("irq.h", HAND_IRQ)
        arguments = ["chip", self.path, "--arch", "armv7m", "--compare", hand, "--cxx", " ".join(COMPILER)]
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(main(arguments), 0)
            self.write(hand, HAND_IRQ.replace("UART_RX = 5", "UART_RX = 3"))
            self.assertEqual(main(arguments), 1)
            self.assertEqual(main(arguments[:-2]), 1)

    def test_a_wrong_or_unknown_arch_is_refused(self):
        report = Report()
        described, board = chip.read(self.path, report)
        for arch in ("rv32imac", "armv8m"):
            with self.subTest(arch=arch):
                with self.assertRaises(chip.Failure):
                    chip.view_of(described, arch)

    def test_a_compiler_that_does_not_run_fails(self):
        with self.assertRaises(chip.Failure):
            chip.compare(self.view(), self.header("irq.h", HAND_IRQ), ["/nonexistent/c++"])

    def test_a_name_in_a_comment_is_not_declared(self):
        hand = self.header("irq.h", HAND_IRQ + "// TIMER_TICK lives elsewhere\n")
        self.assertIn("TIMER_TICK", chip.absent_from(self.view(), hand, "irq.h"))
        self.assertEqual(self.compare("irq.h", HAND_IRQ + "// TIMER_TICK lives elsewhere\n"), None)

    def test_nothing_generated_to_compare_is_refused(self):
        self.write(self.path, SMALL.replace(", lines: { rx: 5, tx: { number: 6, ref: \"p.11\", symbol: UART_TX_IRQ } }",
                                            "").replace(", lines: { tick: 7 }", ""))
        report, said, status = chip.run(self.path, "armv7m", header=self.header("irq.h", HAND_IRQ), compiler=COMPILER)
        self.assertEqual(status, 1)
        self.assertIn("nothing to compare", said[0])

    def test_two_region_units_in_one_build_fail(self):
        text = SMALL.replace("protection: { unit: pmsav7, covers_devices: true, memory_type: true }\n",
                             "cores:\n  big: { protection: { unit: pmsav7, covers_devices: true, memory_type: true } }\n"
                             "  little: { protection: { unit: pmp, covers_devices: true, memory_type: false } }\n")
        self.write(self.path, text)
        with self.assertRaises(chip.Failure):
            chip.generate(self.view())

    def test_an_unserved_request_exits_apart_from_a_refusal(self):
        out = os.path.join(self.scratch, "out")
        with contextlib.redirect_stderr(io.StringIO()):
            status = main(["chip", self.path, "--arch", "rv32imac", "--include-dir", out, "--chip-dir", out])
        self.assertEqual(status, 4)

    def test_a_compare_of_another_header_fails(self):
        with self.assertRaises(chip.Failure):
            chip.run(self.path, "armv7m", header=self.header("chip_tables.h", ""), compiler=COMPILER)

    def test_the_described_chips_keep_the_values_their_headers_had(self):
        golden = {
            ("xmc4800", "armv7m"): ["#define KICKOS_MAX_IRQ 112", "#define KICKOS_CHIP_CYCCNT_GLITCHES 1",
                                    "CCU40_BASE = 0x4000C000u", "SCU_TRAP_BASE = 0x50004160u",
                                    "SCU_PLL_BASE = 0x50004710u", "FLASH0_CTRL_BASE = 0x58001000u",
                                    "FLASH_CACHED_BASE = 0x8000000u", "USIC0_SR0 = 84,", "enum node : int",
                                    "namespace kickos::xmc::mmap"],
            ("stm32f411", "armv7m"): ["#define KICKOS_MAX_IRQ 86", "GPIOA_BASE = 0x40020000u", "GPIO_STRIDE = 0x400u",
                                      "RCC_BASE = 0x40023800u", "FLASH_BASE = 0x40023C00u", "TIM2_IRQ = 28,",
                                      "USART2_IRQ = 38,"],
            ("mk64f", "armv7m"): ["#define KICKOS_MAX_IRQ 86", "SIM_BASE = 0x40048000u", "PORTA_BASE = 0x40049000u",
                                  "PORT_STRIDE = 0x1000u", "UART4_BASE = 0x400EA000u", "GPIO_STRIDE = 0x40u",
                                  "UART0_RXTX_IRQ = 31,", "UART0_ERR_IRQ = 32,"],
            ("esp32c6", "rv32imac"): ["#define KICKOS_MAX_IRQ 32", "#define KICKOS_IRQ_SOFT_ONLY_BASE 26",
                                      "PLIC_MX_BASE = 0x20001000u", "CLINT_BASE = 0x20001800u",
                                      "RTC_WDT_BASE = 0x600B1C00u", "UART0_TX_LINE = 16,", "enum kernel_line : int"],
            ("virt_rv32", "rv32imac"): ["#define KICKOS_MAX_IRQ 32", "#define KICKOS_CHIP_CYCCNT_HZ 0",
                                        "CLINT_BASE = 0x2000000u"],
            ("virt_arm64", "armv8a"): ["#define KICKOS_MAX_IRQ 288", "#define KICKOS_IRQ_FREE_BASE 200",
                                       "#define KICKOS_CHIP_CYCCNT_HZ 0", "GICD_BASE = 0x8000000u",
                                       "GICR_BASE = 0x80A0000u", "UART0_BASE = 0x9000000u",
                                       "#define KICKOS_LAYOUT_DRAM_BASE 0x40000000"],
            ("virt_rv64", "rv64imac"): ["#define KICKOS_MAX_IRQ 32", "#define KICKOS_CHIP_CYCCNT_HZ 0",
                                        "#define KICKOS_LAYOUT_DRAM_SIZE 0x4000000",
                                        "#define KICKOS_LAYOUT_TEST_FINISHER_BASE 0x100000"],
            ("q35", "x86_64"): ["#define KICKOS_MAX_IRQ 24", "COM1_BASE = 0x3F8u", "PIC_MASTER_BASE = 0x20u",
                                "ACPI_PM_BASE = 0x600u"],
            ("imx8mp", "armv8a"): ["#define KICKOS_MAX_IRQ 192", "#define KICKOS_IRQ_FREE_BASE 181",
                                   "#define KICKOS_CHIP_CYCCNT_HZ 0", "GICD_BASE = 0x38800000u",
                                   "UART1_BASE = 0x30860000u", "MU1_A_TO_A53 = 120,",
                                   "#define KICKOS_LAYOUT_GICR_SIZE 0x80000"],
        }
        for (name, arch), lines in sorted(golden.items()):
            text = "".join(chip.generate(self.view(os.path.join(PLATFORM, name, "chip.yaml"), arch)).values())
            for line in lines:
                with self.subTest(chip=name, line=line):
                    self.assertIn(line, text)

    def test_a_board_files_memory_joins_its_chips(self):
        board = "".join(chip.generate(self.view(os.path.join(PLATFORM, "rp2040", "picopi.yaml"), "armv6m")).values())
        alone = "".join(chip.generate(self.view(os.path.join(PLATFORM, "rp2040", "chip.yaml"), "armv6m")).values())
        for line in ("XIP_FLASH_BASE = 0x10000000u", "#define KICKOS_LAYOUT_XIP_FLASH_SIZE 0x200000",
                     "#define KICKOS_LINK_FLASH FLASH (rx) : ORIGIN = 0x10000000, LENGTH = 0x200000",
                     "set(KICKOS_CHIP_LINK_FLASH_ORIGIN 0x10000000)", "and platform/rp2040/picopi.yaml"):
            with self.subTest(line=line):
                self.assertIn(line, board)
                self.assertNotIn(line, alone)

    def test_a_board_bus_names_its_pins_selectors_and_base(self):
        board = chip.generate(self.view(os.path.join(PLATFORM, "mk64f", "frdmk64f.yaml")))["board_buses.h"]
        for line in ("{3u, 1u, 2u}, /* PTD1 alt2: dspi0.sck */", "{3u, 3u, 2u}, /* PTD3 alt2: dspi0.sin */",
                     "spi0_chip_selects[] = {\n        {2u, 4u}, /* PTC4 */",
                     '{"spi0", 0x4002C000u, spi0_pins, 3u, spi0_chip_selects, 1u},', "bus_count = 1u;",
                     "namespace kickos::mk64f::board", "and platform/mk64f/frdmk64f.yaml"):
            with self.subTest(line=line):
                self.assertIn(line, board)
        alone = chip.generate(self.view(os.path.join(PLATFORM, "mk64f", "chip.yaml")))["board_buses.h"]
        self.assertIn("inline constexpr bus const* buses = nullptr;\n    inline constexpr uint32_t bus_count = 0u;",
                      alone)

    def test_a_bus_over_a_channel_takes_the_channels_base(self):
        board = self.small_board("PA1: { alt2: usic.ch0.sclk, gpio: port.0.1 }")
        text = chip.generate(self.view(board))["board_buses.h"]
        self.assertIn('{"spi0", 0x40020000u, spi0_pins, 1u, spi0_chip_selects, 1u},', text)
        self.assertIn("{0u, 1u, 2u}, /* PA1 alt2: usic.ch0.sclk */", text)
        self.assertIn("{0u, 2u}, /* PA2 */", text)

    def test_a_bus_pin_carrying_its_device_twice_is_refused(self):
        board = self.small_board("PA1: { alt1: usic.ch0.dout0, alt2: usic.ch0.sclk, gpio: port.0.1 }")
        with self.assertRaisesRegex(chip.Failure, "bus `spi0` pin `PA1` carries `/dev/usic/ch0` at the "
                                                  "selectors `alt1`, `alt2`"):
            chip.generate(self.view(board))

    def test_a_bus_pin_whose_selector_names_no_mux_value_is_refused(self):
        board = self.small_board("PA1: { fn: usic.ch0.sclk, gpio: port.0.1 }")
        with self.assertRaisesRegex(chip.Failure, "bus `spi0` pin `PA1` carries `/dev/usic/ch0` at `fn`, "
                                                  "which names no mux value"):
            chip.generate(self.view(board))

    def test_a_bus_pin_with_no_gpio_function_is_refused(self):
        board = self.small_board("PA1: { alt2: usic.ch0.sclk }")
        with self.assertRaisesRegex(chip.Failure, "bus `spi0` pin `PA1` has no `gpio` function"):
            chip.generate(self.view(board))

    def small_board(self, pin):
        self.write(self.path, SMALL + "pins:\n  %s\n  PA2: { gpio: port.0.2 }\n" % pin)
        board = os.path.join(self.platform, "tiny.yaml")
        self.write(board, "version: 1\nboard: tiny\nchip: small\nconsole: { device: /dev/uart }\nbuses:\n"
                          "  spi0: { device: /dev/usic/ch0, pins: [PA1], chip_selects: [PA2] }\n")
        return board

    def test_each_window_states_its_size(self):
        rp2040 = chip.generate(self.view(os.path.join(PLATFORM, "rp2040", "chip.yaml"), "armv6m"))["chip_mmap.h"]
        self.assertIn("USBCTRL_SIZE = 0x20000u;", rp2040)
        f411 = chip.generate(self.view(os.path.join(PLATFORM, "stm32f411", "chip.yaml"), "armv7m"))["chip_mmap.h"]
        self.assertIn("GPIO_SIZE = 0x400u;", f411)
        xmc = chip.generate(self.view(os.path.join(PLATFORM, "xmc4800", "chip.yaml"), "armv7m"))["chip_mmap.h"]
        self.assertIn("USIC0_CH0_SIZE = 0x200u;", xmc)

    def test_a_unit_no_build_drives_is_no_build_region_unit(self):
        outputs = chip.generate(self.view(os.path.join(PLATFORM, "sam3x8e", "chip.yaml"), "armv7m"))
        self.assertIn('set(KICKOS_CHIP_REGION_UNIT "")', outputs["chip.cmake"])
        outputs = chip.generate(self.view(os.path.join(PLATFORM, "stm32f411", "chip.yaml"), "armv7m"))
        self.assertIn('set(KICKOS_CHIP_REGION_UNIT "pmsav7")', outputs["chip.cmake"])

    def test_a_board_file_names_its_chip(self):
        board = os.path.join(PLATFORM, "xmc4800", "xmc4800-relax.yaml")
        self.assertEqual(self.view(board).chip.name, "xmc4800")

    def test_the_board_pins_follow_the_board_file(self):
        def pins(chip_name, board, arch="armv7m"):
            return chip.generate(self.view(os.path.join(PLATFORM, chip_name, board + ".yaml"), arch))["board_pins.h"]

        disco = pins("stm32f411", "f411disco")
        for line in ("#define KICKOS_BOARD_CONSOLE_BASE 0x40004400 /* /dev/usart2 */",
                     "#define KICKOS_BOARD_CONSOLE_TX_PORT 0\n", "#define KICKOS_BOARD_CONSOLE_TX_PORT_BASE 0x40020000\n",
                     "#define KICKOS_BOARD_CONSOLE_TX_BIT 2\n", "#define KICKOS_BOARD_CONSOLE_RX_SELECT 7 ",
                     "#define KICKOS_BOARD_LED_PORT 3\n", "#define KICKOS_BOARD_LED_PORT_BASE 0x40020C00\n",
                     "#define KICKOS_BOARD_LED_BIT 12\n", "#define KICKOS_BOARD_LED_ACTIVE_LOW 0\n",
                     "and platform/stm32f411/f411disco.yaml"):
            with self.subTest(line=line):
                self.assertIn(line, disco)
        black = pins("stm32f411", "blackpill")
        self.assertIn("#define KICKOS_BOARD_LED_PORT 2\n", black)
        self.assertIn("#define KICKOS_BOARD_LED_ACTIVE_LOW 1\n", black)
        # An input path selects no mux value.
        xmc = pins("xmc4800", "xmc4800-relax")
        self.assertIn("#define KICKOS_BOARD_CONSOLE_DOUT0_SELECT 2 ", xmc)
        self.assertNotIn("KICKOS_BOARD_CONSOLE_DX0_SELECT", xmc)
        self.assertIn("#define KICKOS_BOARD_CONSOLE_DX0_INPUT_SELECT 1 ", xmc)
        # A port device that does not repeat names no index.
        rp = pins("rp2040", "picopi", "armv6m")
        self.assertNotIn("KICKOS_BOARD_LED_PORT ", rp)
        self.assertIn("#define KICKOS_BOARD_CONSOLE_TX_SELECT 2 ", rp)
        self.assertIn("#define KICKOS_BOARD_CONSOLE_TX_SELECT 0 ", pins("sam3x8e", "due"))
        self.assertIn("#define KICKOS_BOARD_CONSOLE_RX_INPUT_SELECT 1 ", pins("imxrt1062", "teensy41"))
        self.assertIn("#define KICKOS_BOARD_CONSOLE_TXD_SELECT 11 ", pins("rx72m", "rx72m", "rxv3"))
        self.assertNotIn("KICKOS_BOARD_LED", pins("rp2350", "pizero2350"))
        # An addressable LED has a pin and no level.
        c6 = pins("esp32c6", "esp32c6-wroom", "rv32imac")
        self.assertIn("#define KICKOS_BOARD_LED_BIT 8\n", c6)
        self.assertIn("#define KICKOS_BOARD_LED_ADDRESSABLE 1\n", c6)
        self.assertNotIn("KICKOS_BOARD_LED_ACTIVE_LOW", c6)
        # Consecutive reserved bits of one port are one run.
        esp32 = pins("esp32", "esp32-wroom", "lx6")
        self.assertIn("#define KICKOS_BOARD_RESERVED_RUNS(RUN) RUN(0x3FF44000, 6, 11) /*", esp32)
        self.assertIn("#define KICKOS_BOARD_RESERVED_RUNS(RUN) RUN(0x60091000, 9, 9) RUN(0x60091000, 12, 13) "
                      "RUN(0x60091000, 15, 15) /*", c6)
        self.assertIn("#define KICKOS_BOARD_RESERVED_RUNS(RUN) /*", disco)
        # The console pins, the kernel LED and every reserved pin, each by its port's base.
        self.assertIn("#define KICKOS_BOARD_KERNEL_PINS(PIN) PIN(0x40020000, 2) PIN(0x40020000, 3) "
                      "PIN(0x40020C00, 12) /*", disco)
        self.assertIn("#define KICKOS_BOARD_KERNEL_PINS(PIN) PIN(0x3FF44000, 1) PIN(0x3FF44000, 3) PIN(0x3FF44000, 2) "
                      "PIN(0x3FF44000, 6) PIN(0x3FF44000, 7) PIN(0x3FF44000, 8) PIN(0x3FF44000, 9) "
                      "PIN(0x3FF44000, 10) PIN(0x3FF44000, 11) /*", esp32)
        self.assertIn("#define KICKOS_BOARD_KERNEL_PINS(PIN) PIN(0x401B8000, 2) PIN(0x401B8000, 3) "
                      "PIN(0x401BC000, 3) /*", pins("imxrt1062", "teensy41"))

    def test_a_chip_file_alone_wires_no_pin(self):
        alone = chip.generate(self.view(os.path.join(PLATFORM, "stm32f411", "chip.yaml")))["board_pins.h"]
        self.assertNotIn("#define", alone.replace("#define KICKOS_BOARD_PINS_H", ""))

    def test_a_selector_names_its_mux_value(self):
        for selector, value in (("a", 0), ("c", 2), ("af7", 7), ("psel11", 11), ("f2", 2), ("remap0", 0),
                                ("in", None), ("gpio", None), ("alt", None)):
            with self.subTest(selector=selector):
                self.assertEqual(chip.selector_value(selector), value)

    def test_two_runs_write_the_same_bytes(self):
        boards = sorted(os.path.join(PLATFORM, name, board) for name in os.listdir(PLATFORM)
                        for board in os.listdir(os.path.join(PLATFORM, name)) if board != "chip.yaml")
        self.assertGreater(len(boards), 15)
        outputs = []
        for seed in ("1", "2"):
            out = os.path.join(self.scratch, "seed" + seed)
            for board in boards:
                name = os.path.basename(os.path.dirname(board))
                stem = os.path.splitext(os.path.basename(board))[0]
                env = dict(os.environ, PYTHONHASHSEED=seed)
                subprocess.run([sys.executable, "-m", "kickos_compose", "chip", board, "--arch", ARCHES[name],
                                "--include-dir", os.path.join(out, stem, "include"),
                                "--chip-dir", os.path.join(out, stem, "chip")],
                               check=True, env=env, cwd=COMPOSE, stdout=subprocess.DEVNULL)
            outputs.append(tree_bytes(out))
        self.assertGreater(len(outputs[0]), len(boards) * len(chip.CHIP_OUTPUTS))
        self.assertEqual(outputs[0], outputs[1])


def tree_bytes(root):
    """{path under root: bytes} of every file under root."""
    found = {}
    for dirpath, dirnames, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            with open(path, "rb") as stream:
                found[os.path.relpath(path, root)] = stream.read()
    return found
