#!/usr/bin/env python3
# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# RP2040 second-stage bootloader (boot2) checksum tool. The RP2040 bootrom loads
# the first 256 bytes of flash into SRAM and, before jumping to them, verifies a
# CRC over the first 252 bytes stored little-endian at offset 0x0FC. The CRC is
# CRC-32/MPEG-2: poly 0x04C11DB7, init 0xFFFFFFFF, no input/output reflection,
# no final XOR (RP2040 datasheet section 2.8.1.3.1).
#
# Reads a raw boot2 binary (<= 252 bytes), pads to 252, appends the 4-byte CRC,
# and emits an assembly file placing the 256-byte block in the .boot2 section.

import sys


def crc32_mpeg2(data: bytes) -> int:
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte << 24
        for _ in range(8):
            if crc & 0x80000000:
                crc = ((crc << 1) ^ 0x04C11DB7) & 0xFFFFFFFF
            else:
                crc = (crc << 1) & 0xFFFFFFFF
    return crc


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: rp2040_checksum.py <boot2.bin> <out.S>\n")
        return 2
    raw = open(sys.argv[1], "rb").read()
    if len(raw) > 252:
        sys.stderr.write("boot2 too large: %d > 252 bytes\n" % len(raw))
        return 1
    body = raw + b"\x00" * (252 - len(raw))
    crc = crc32_mpeg2(body)
    blob = body + crc.to_bytes(4, "little")

    lines = [
        "/* Generated by rp2040_checksum.py -- do not edit. */",
        "    .section .boot2, \"a\"",
        "    .global g_rp2040_boot2",
        "g_rp2040_boot2:",
    ]
    for i in range(0, 256, 16):
        chunk = ", ".join("0x%02x" % b for b in blob[i:i + 16])
        lines.append("    .byte " + chunk)
    open(sys.argv[2], "w").write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
