# SPDX-License-Identifier: CECILL-C
# Copyright (c) 2026 Philippe Leduc
#
# Which arms of one selftest image its arena can back, read off the image's sizing link: the arena
# past the boot replay's last block, against each arm's arena blocks and the default stacks of its
# workers, in registration order. Writes the arms left out and the image's seat as a C++ source,
# the same names one per line for the gates, and the link script whose ASSERT is the exact backstop.
#
#   python3 arena_fit.py <sizing elf> <nm> <objcopy> <workers file> <worker pool> <stack align>
#           <stack stride> prefix=<C symbol prefix> <bitmap bytes> list|refuse <out .cc> <out .txt>
#           <out .ld> <image>
#
# `refuse` (an emulator board) fails the build where any arm is left out.

import os
import re
import subprocess
import sys
import tempfile


def align_up(value, align):
    return (value + align - 1) // align * align


def symbols(nm, elf):
    out = {}
    text = subprocess.run([nm, elf], check=True, capture_output=True, text=True).stdout
    for line in text.splitlines():
        parts = line.split()
        if len(parts) == 3:
            out[parts[2]] = int(parts[0], 16)
    return out


def records(objcopy, elf):
    """[(arm, [(ask, bytes, align)])] in registration order."""
    with tempfile.TemporaryDirectory() as tmp:
        raw = os.path.join(tmp, 'arms.bin')
        subprocess.run([objcopy, '--dump-section', '.kickos_arena_arm=' + raw, elf, os.devnull],
                       check=True, capture_output=True)
        with open(raw, 'rb') as fh:
            data = fh.read()
    out = []
    at = 0

    def text():
        nonlocal at
        end = data.index(b'\0', at)
        word = data[at:end].decode()
        at = end + 1
        return word

    def word():
        nonlocal at
        value = int.from_bytes(data[at:at + 4], 'little')
        at += 4
        return value

    while at < len(data):
        arm = text()
        count = data[at]
        at += 1
        asks = []
        for _ in range(count):
            asks.append((text(), word(), word()))
        out.append((arm, asks))
    return out


def main(argv):
    (elf, nm, objcopy, workers_file, pool, stack_align, stack_stride, prefix, bitmap_bytes, mode,
     out_cc, out_txt, out_ld, image) = argv[1:]
    pool = int(pool)
    prefix = prefix[len('prefix='):]
    stack_align = int(stack_align)
    stack_stride = int(stack_stride)
    sym = symbols(nm, elf)
    placed = sorted((int(m.group(1)), name) for name in sym
                    for m in [re.match(r'^__kickos_system_arena_(\d+)$', name)] if m)
    booted_name = prefix + '__kickos_ram_start'
    if placed:
        booted_name = placed[-1][1]
    booted = sym[booted_name]
    end = sym[prefix + '__kickos_ram_end']
    workers = {}
    with open(workers_file) as fh:
        for line in fh:
            name, count = line.split()
            workers[name] = int(count)
    # A left-out arm stays linked and the bitmap keeps its size, so the image's arena equals the
    # sizing link's.
    start = align_up(booted, stack_align)
    seat = 0
    held = {}
    left_out = []
    bitmap = [0] * int(bitmap_bytes)
    for index, (arm, asks) in enumerate(records(objcopy, elf)):
        want = workers.get(arm, 0)
        if want > pool:
            want = 0  # refused by its own ask, so it seats nothing
        trial_seat = max(seat, want)
        trial = dict(held)
        for ask, size, align in asks:
            trial[ask] = (size, align)
        most = max([a for s, a in trial.values()] + [1])
        top = align_up(start + trial_seat * stack_stride, most) + sum(s for s, a in trial.values())
        if top > end:
            left_out.append(arm)
            bitmap[index // 8] |= 1 << (index % 8)
            continue
        seat = trial_seat
        held = trial
    most = max([a for s, a in held.values()] + [1])
    total = sum(s for s, a in held.values())
    with open(out_cc, 'w') as fh:
        fh.write('// GENERATED by arena_fit.py for %s.\n' % image)
        fh.write('namespace selftest\n{\n')
        fh.write('    extern __attribute__((visibility("hidden"))) unsigned char const st_left_out[%d] = {%s};\n'
                 % (len(bitmap), ', '.join(str(b) for b in bitmap)))
        fh.write('    extern __attribute__((visibility("hidden"))) int const st_seat_workers = %d;\n}\n'
                 % seat)
    with open(out_txt, 'w') as fh:
        fh.write(''.join(arm + '\n' for arm in left_out))
    with open(out_ld, 'w') as fh:
        fh.write('/* GENERATED by user/apps/common/selftest/arena_fit.py for %s. */\n\n' % image)
        fh.write('__kickos_arena_ask_top = ALIGN(ALIGN(%s, %d) + %d * %d, %d) + %d;\n'
                 % (booted_name, stack_align, seat, stack_stride, most, total))
        fh.write('ASSERT(__kickos_arena_ask_top <= %s__kickos_ram_end,\n'
                 '       "selftest: the arena cannot back, past the boot and the worker stacks this '
                 'image seats at start, the blocks its arms reserve then; __kickos_arena_ask_top - '
                 '__kickos_ram_end in its map is how far short.");\n' % prefix)
    if left_out:
        print('selftest: %s leaves out %s (its arena is %d B past the boot)'
              % (image, ', '.join(left_out), end - start))
        if mode == 'refuse':
            print('selftest: %s runs on an emulator, where every arm runs: refused for leaving out %s'
                  % (image, ', '.join(left_out)), file=sys.stderr)
            for out in (out_cc, out_txt, out_ld):
                os.remove(out)
            return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
